version: '3.8'

services:
  edgecom-nat:
    container_name: nat
    build:
      context: ./nat
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    cap_add:
      - NET_ADMIN
    networks:
      privnet:
        aliases:
          - nat.free5gc.org


  free5gc-upf:
    container_name: upf
    #image: put_image_req_here
    build:
      context: ./eupf
    privileged: true
    command: --iface eth0 --nodeid upf.free5gc.org
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
    environment:
      GIN_MODE: release
    ulimits:
      memlock: -1
    cap_add:
      - BPF
#      - TRACING
      - PERFMON
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE # setrlimit
    ports:
      - "8080:8080"
      - "9090:9090"
    sysctls:
      - net.ipv4.conf.all.forwarding=1
    networks:
      privnet:
        aliases:
          - upf.free5gc.org

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9091:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      privnet:

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      privnet:

volumes:
  prom_data:
